### ISSUE TITLE
Contact custom properties seem to be missing

### ISSUE THREAD

**Issue by Fedduh** [HubSpot/hubspot-api-php#204]
Hi,

For getting a contact, we also specify which custom properties te get for this contact. We have used the example code in this repo for that. This used to work. But since a while the requested properties return empty, even though they have values for this customer in Hubspot.

Did something change in this? Is anyone else experiencing this?

$searchRequest->setProperties(['custom_a', 'custom_b']);
The search result does include these fields. But their values are empty.
(I've verified that custom_a and custom_b are the internal unique names in Hubspot)

```
	public function getContact($email)
	{
		$filter = new \HubSpot\Client\Crm\Contacts\Model\Filter();

		$filter
			->setOperator('EQ')
			->setPropertyName('email')
			->setValue($email);

		$filterGroup = new \HubSpot\Client\Crm\Contacts\Model\FilterGroup();
		$filterGroup->setFilters([$filter]);

		$searchRequest = new \HubSpot\Client\Crm\Contacts\Model\PublicObjectSearchRequest();
		$searchRequest->setFilterGroups([$filterGroup]);
		$searchRequest->setProperties(['custom_a', 'custom_b']);

		try {
			$contactsPage = json_decode($this->hubSpot->crm()->contacts()->searchApi()->doSearch($searchRequest));
		} catch (\Throwable $t) {
			return false;
		}

		if ($contactsPage->total === 0) {
			return false;
		}

		return $contactsPage->results;
	}
```

PHP 7.0.33
"hubspot/api-client": "2.8.1",

**Comment by pragna-php** [comment]
Hello @Fedduh 

I have used the same for filtering data based on updated date but in the result not getting the custom properties which I already mentioned in the setproperty function. Can you please check why I am not getting the custom property? because as per the ReadME changes it should work. 

$filter = new Filter();
$filter->setPropertyName('lastmodifieddate')
       ->setOperator('GT')
       ->setValue($updatedAt);

// Create the filter group and add the filter
$filterGroup = new FilterGroup();
$filterGroup->setFilters([$filter]);

// Create the search request and set the filter group and properties
$searchRequest = new PublicObjectSearchRequest();
$searchRequest->setFilterGroups([$filterGroup]);
$searchRequest->setProperties(['preferences']);//'firstname', 'lastname', 'email', 

// Execute the search
$response = $this->hubSpot->crm()->contacts()->searchApi()->doSearch($searchRequest);
$contactResult = $response->getResults();
dd($contactResult);

waiting for your response!

**Comment by Fedduh** [comment]
> Hello @Fedduh
> 
> I have used the same for filtering data based on updated date but in the result not getting the custom properties which I already mentioned in the setproperty function. Can you please check why I am not getting the custom property? because as per the ReadME changes it should work.
> 
> $filter = new Filter(); $filter->setPropertyName('lastmodifieddate') ->setOperator('GT') ->setValue($updatedAt);
> 
> // Create the filter group and add the filter $filterGroup = new FilterGroup(); $filterGroup->setFilters([$filter]);
> 
> // Create the search request and set the filter group and properties $searchRequest = new PublicObjectSearchRequest(); $searchRequest->setFilterGroups([$filterGroup]); $searchRequest->setProperties(['preferences']);//'firstname', 'lastname', 'email',
> 
> // Execute the search $response = $this->hubSpot->crm()->contacts()->searchApi()->doSearch($searchRequest); $contactResult = $response->getResults(); dd($contactResult);
> 
> waiting for your response!

Sorry I can't help you. This post is more than a year old and I no longer work at that employer and currently don't use PHP. 

I am also not a contributer of this package. I think it's best that you open a new issue on GitHub with your question :)
